export MIP_IDS=${MIP_IDS:=}
export LIB_NAMES=${LIB_NAMES:=}
export PUBLISHED_NAMES=${PUBLISHED_NAMES:=}
export RELEASE_NAMES=${RELEASE_NAMES:=}
export TAG_VALUES=${TAG_VALUES:=}
export EXCLUDED_TAG_VALUES=${EXCLUDED_TAG_VALUES:=}

export JOB_LOGPREFIX=${JOB_LOGPREFIX:=${LOGS_DIR}/tag}
