BASE_EXPORT_FOLDER=${BASE_EXPORT_FOLDER:=/nrs/neuronbridge}
DATA_VERSION=${DATA_VERSION:=3.0.0}

export EXPORTED_DATA_VERSION=${EXPORTED_DATA_VERSION="${DATA_VERSION}"}
export EXPORT_DIR=${EXPORT_DIR:="${BASE_EXPORT_FOLDER}/v${DATA_VERSION}"}
export JACS_URL=${JACS_URL:="http://host/api/rest-v2"}
export JACS_AUTH_TYPE=${JACS_AUTH_TYPE:="APIKEY"}
export JACS_AUTH_TOKEN=${JACS_AUTH_TOKEN:="tokenvalue"}

export BRAIN_STORE=${BRAIN_STORE:="fl:open_data:brain"}
export VNC_STORE=${VNC_STORE:="fl:open_data:vnc"}

export JOB_LOGPREFIX=${JOB_LOGPREFIX:="${LOGS_DIR}/exports"}
export READ_BATCH_SIZE=2000
export PROCESSING_PARTITION_SIZE=${PROCESSING_PARTITION_SIZE:=20}

export EXPORT_OFFSET=${EXPORT_OFFSET:=0}
export EXPORT_SIZE=${EXPORT_SIZE:=0}
